### ISSUE TITLE
Moderate only certain profile types?

### ISSUE THREAD

**Issue by hellodanevans** [WebDevStudios/BuddyPress-Registration-Options#199]
We can't seem to find any way to only approve certain profiles types - or auto-approve certain profile types - when using with BuddyBoss. I think it would be an extremely useful feature as many buddypress sites have these customer/seller, student/teacher style userbase where it would be really important for site admins to approve one and not the other. Thanks in advance and please let me know if I'm in the wrong place for this suggestion :)

**Comment by tw2113** [comment]
I know I had a similar request a couple months back over at https://wordpress.org/support/topic/approval-for-only-one-profile-type/ and in the end deduced that I didn't have enough information at the time regarding BuddyBoss, to work up a solution that would work, and that even bubbled over at the time to BuddyPress as well.

Also with that, I haven't circled back to the topic and idea since then either, so I'm still in that same position.

Willing to leave the issue open here, but I don't have anything for it at this time.

**Comment by hellodanevans** [comment]
Hi Michael,

Sorry yes that was me also, we're revisiting it now after putting it on hold.

Would you be interested in us commissioning the work?

Best regards,

Dan Evans
Marketing Manager
& Head of Candidate Attraction
[Logo]<https://www.grb.uk.com/>
***@***.***<https://www.instagram.com/thegrbteam/>

Graduate Recruitment Bureau
E: ***@***.******@***.***>
T: 01273 715963
www.grb.uk.com<http://www.grb.uk.com/>

**Comment by tw2113** [comment]
Aha.

How soon are you needing this? Asking because I know with the holidays here, and a contributor day next week coming up, I would have more dedicated time that I could look into this, without having to go the commission route.

**Comment by hellodanevans** [comment]
Hi Michael,

Thank you for the quick reply!

I'm just working on the site over the holidays and into January, hoping to launch something in Feb, maybe March so it's not a huge rush. We're moving our site https://graduatementor.uk onto BuddyBoss to give us more power of user community features. It's great platform, free mentoring from senior professionals in industry for the younger generations. Just something we're doing on the side so currently a not-for-profit.

That said, we would be happy to pay for someone to work on this feature but it would be even more amazing if the original developer would consider the feature if/when you have time.

Please let me know your thoughts?

Best regards,

Dan Evans
Marketing Manager
& Head of Candidate Attraction
[Logo]<https://www.grb.uk.com/>
***@***.***<https://www.instagram.com/thegrbteam/>

Graduate Recruitment Bureau
E: ***@***.******@***.***>
T: 01273 715963
www.grb.uk.com<http://www.grb.uk.com/>

**Comment by tw2113** [comment]
You're using https://www.buddyboss.com/product/buddypress-member-types/ for your site correct? I may not be able to solve this one as that's a premium plugin and not something inside the base platform. Not sure if they'd be willing to provide a copy to WebDevStudios for interoperability purposes or at least answer questions regarding when membership types get assigned and on what priority for the hooks.

**Comment by hellodanevans** [comment]
Hi there, no we’re just using the native buddy/
boss ‘profile types’, it’s not a plugin.

https://www.buddyboss.com/resources/docs/components/profiles/profile-types/

Thanks

Dan Evans
grb.uk.com
________________________________

**Comment by tw2113** [comment]
Didn't see those settings for adding to registration form, sorry about that.

Anyways, based on that, I think this may work:

```
function hellodanevans( $user_id, $user_login, $user_password, $user_email, $usermeta ) {
	// Single value version.
	if ( "60" == $usermeta['field_4'] ) {
		bp_registration_set_moderation_status( $user_id, 'false' );
		return;
	}

	// Multiple possible profile types to NOT moderate
	if ( in_array( $usermeta['field_4'], [ '60', '61' ] ) ) {
		bp_registration_set_moderation_status( $user_id, 'false' );
		return;
	}
}
add_action( 'bp_core_signup_user', 'hellodanevans', 10, 5 );
```

You're going to need to determine which field in your `$usermeta` variable will hold the profile type IDs, and also determine which IDs correlate to which profile type. 

For example, I was at `/wp-admin/admin.php?page=bp-profile-setup` in my BuddyBoss local and on the Profile Fields tab, and "Details (Signup)" subtab.

Had the out of box standard first name, last name, nickname. Then I added one more related to selecting a profile type. Thus `field_4`.

On the `/wp-admin/edit.php?post_type=bp-member-type` page aka Profile Types tab, I had "teacher", and "student" for profile types, with teacher resulting in an ID of 60, and student getting 59. The 61 id from the second example is just a quick dummy value in case you want to have multiple profile types not moderated.

Give this a go.

**Comment by hellodanevans** [comment]
Hi, this worked perfectly, many thanks!

**Comment by tw2113** [comment]
Honestly not presently sure how to handle that part, since this solution basically overrides after the fact with all the parts that our core plugin is set up and intended to do. We never really intended it to be able to not do its thing conditionally, every user was supposed to go through the process.

Alternative solution for this off the top of my head would be to send an extra email afterwards saying they were auto-approved, perhaps reusing our already existing "approved" message spot, or something else.

**Comment by hellodanevans** [comment]
What about disabling all emails from the plugin? Admin doesn't need an alert and there are notifications on members profile explaining it's restricted.

**Comment by tw2113** [comment]
Admittedly no on that part as well, since some of them are triggered as part of approval processes in general. Based on what I recall and have seen as of late since I've been in the plugin code a fair amount lately, I'd need to rework a number of things to find a way to either change when the emails are sent, or nullify email sending conditionally.

I just don't have answers right now on how to potentially do that right now in ways that would work.

**Comment by hellodanevans** [comment]
Fair enough, thank you for the quick replies
